# Generated by Django 5.0.6 on 2024-07-12 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_payment_card_number_alter_payment_cvc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.connect', verbose_name='Connect'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='CVC'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
