# Generated by Django 5.0.6 on 2024-07-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_payment_connect_alter_payment_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='mark',
            field=models.BooleanField(default=1, verbose_name='mark:'),
            preserve_default=False,
        ),
    ]
