# Generated by Django 5.0.6 on 2024-07-19 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_telegramprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.IntegerField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='CVC'),
        ),
    ]
